language: r

warnings_are_errors: true

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  echo 'before script:'
  Rscript -e 'devtools::install()'
  Rscript -e 'devtools::session_info("testsysfile")'
