language: r

warnings_are_errors: true

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - echo "before script:"
  - R -e "devtools::install_github('kbroman/testsysfile')"
  - R -e "devtools::session_info('testsysfile')"

after_script:
  - echo 'after script:'
  - R -e "devtools::install_github('kbroman/testsysfile')"
  - R -e "devtools::session_info('testsysfile')"

after_success:
  - echo 'after success:'
  - R -e "devtools::install_github('kbroman/testsysfile')"
  - R -e "devtools::session_info('testsysfile')"

after_failure:
  - echo 'after failure:'
  - R -e "devtools::install_github('kbroman/testsysfile')"
  - R -e "devtools::session_info('testsysfile')"
