language: r

warnings_are_errors: true

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - echo 'before script:'
  - R CMD INSTALL testsysfile
  - Rscript -e 'devtools::session_info("testsysfile")'

after_script:
  - echo 'after script:'
  - R CMD INSTALL testsysfile
  - Rscript -e 'devtools::session_info("testsysfile")'

after_success:
  - echo 'after success:'
  - R CMD INSTALL testsysfile
  - Rscript -e 'devtools::session_info("testsysfile")'

after_failure:
  - echo 'after failure:'
  - Rscript -e 'devtools::session_info("testsysfile")'
