language: r

warnings_are_errors: true

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

after_failure:
  R -e 'devtools::session_info()'
  cat *.Rcheck/00check.log

after_success:
  R -e 'devtools::session_info()'
